# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 856dc63c05bff03b74b3c99d69ad36ec4ae12a8899c886ec6b185186e8df62a228d845fc7253409e0301f4f18c9d2af4b22122a39e92c6aa714ea318a6a863ff

test:
  secret_key_base: 848f0ee1d3fdf431ada89acc5a319f1a2b26f8d85c40af4868f709f6fe4cdcccbc7433cdd78f364d00e3db9b735b32600feb536bb7d76ca8e89567485436b604

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
